import Head from 'next/head'
import News from '../components/News';
export default function Home({ news }) {
  console.log(news)
  return (
    <div className='w-[50%] ml-auto mr-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        {
          news.map((news) => (
            <News
              key={news.title}
              title={news.title}
              description={news.description}
              urlToImage={news.urlToImage}
              url={news.url}
            />
          ))
        }
      </main>

      <footer >

      </footer>
    </div>
  )
}
export async function getServerSideProps() {
  const news = await fetch("https://saurav.tech/NewsAPI/top-headlines/category/health/in.json").then((res) => res.json());
  return {
    props: {
      news: news.articles
    }
  }
}
